apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: server-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-backend
  template:
    metadata:
      labels:
        app: server-backend
    spec:
      containers:
        - name: server-backend
          image: mooaz/greenminds-server:v1
          ports:
            - containerPort: 3001
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets1
                  key: MONGO_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets1
                  key: MONGO_PASSWORD
            - name: MONGO_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets1
                  key: MONGO_DB_NAME
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets1
                  key: PORT
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mongo-secrets1
                  key: JWT_SECRET_KEY
---

apiVersion: v1
kind: Service
metadata:
  name: server-backend-service
spec:
  selector:
    app: server-backend
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
    nodePort: 31100
